spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true  
#    generate-ddl: true    
    hibertnate.ddl-auto: validate    
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
#    data: classpath:/database/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibertnate.ddl-auto: create-drop