spring:
  main:
    show-banner: true
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES    
---            
spring:
  profiles: local 
server:
  port: 8083