spring:
  main:
    show-banner: true
  velocity:
    charSet: UTF-8        
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
---
spring:
  profiles: local
server:
  port: 8082